from agents_state import AgentState
from langchain_ollama import ChatOllama
from langchain.schema import SystemMessage, HumanMessage, AIMessage
from utils.db_utils import obtain_header
from agents.llm import llm

def verifier_agent(state: AgentState) -> AgentState:

    header = obtain_header(state["csv_path"] + state["csv_file"]) 
    system = SystemMessage(
        content=(
            "You are a professional SQL code verifier called verifier_agent."
            "The first word you return must either be Pass or Fail."
        )
    )
    history = state["messages"]

    user = HumanMessage(
        content=(
            f"Verify the sql query generated by the coder agent passes all four tests:\n"
            f"1. It can be executed on the file: \nsales_database\n given the following header: \n{header}\n"
            f"2. It satisfies the following request:\n{state['user_query']}\n" 
            "3. The syntax is correct to run on a sqlite3 database.\n"
            "4. If there are no other considerations you believe are important that need to be addressed"
            "If it passes all four tests, you must first return Pass. Otherwise, you must first return Fail.\n"
            "Afterwards, give a brief explanation of why it passes or fails.\n"
        )
    )

    all_messages = [system, *history, user]

    ai_response = llm.invoke(all_messages).content.strip()
    print(f"\nVerification of the sql query (Verifier):\n{ai_response}\n")

    verification_status = ai_response.split()[0].strip()[0:4]
    if verification_status not in ["Pass", "Fail"]:
        raise ValueError(f"Unexpected verification status: {verification_status}")
    
    #If verificaiton pass dont update messages
    if verification_status == "Pass":
        return {**state, "verification_status": verification_status}
    return {**state, "verification_status": verification_status, "messages": [user, AIMessage(content=ai_response, name="verifier_agent")]}
